server:
  port: 8080


spring:
  h2:
    console:
      enabled: true
      path: /h2
      # localhost:8080/h2 ? ???? ?.
  datasource:
    url: jdbc:h2:~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create   #???? 'ddl-auto' ?? ??? 'create-drop'
        # -'none': ? ? ???? ????, ?? ???? ?? ?? ?? ????? ???? ???.
        # -'create': ?? ?? ??? ?? '????? ? drop ?? ?? ??? create ?? ?????? ??'??.
        # -'create-drop': 'create'? ????, '??????? ??? ? drop ??? DB? ???
      #                 ??? ??? ? ????? ? ??'??.
    # show-sql: true #??? ????? ?? 'format_sql'? ?? ??? ??? ????...
                     # ?? ?? ?~ ??? org.hibernate.SQL: DEBUG ? ????? ??? ????? ??.
    defer-datasource-initialization: true #?? DB? ?? ????? ????, ?? ?? ???? ?? ???? ???? ??? ?????? ?? ?
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        default_batch_fetch_size: 1000 # '?? ?? V3.1: ???? DTO? ?? - ???? ?? ??'?.
          # ???, ??? ??? ? ??? ??? ???.
        # ?? ??? ??? ???? 500~1000?? ?? ? ??


  messages:
    basename: messages #??? ??? ??? ??(??? ??)? ??? 'messages'?? ???? ?
    #'??? ??'-->'messages.properties'? ?????. ??? 'messages'? ?? ?? 'yml ??'?? ???
    #'basename: messages'? 'messages'? ???? ??? ?!


  devtools:
    livereload:
      enabled: true


logging:
  level:
    org:
      springframework: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type: trace
    hibernate: DEBUG

